# Build Stage:
FROM golang:1.18

## Install build dependencies.
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git

## Add Source Code
ADD . /kconnect
WORKDIR /kconnect

## Build Step
RUN git submodule init
RUN git submodule update
RUN go mod tidy
RUN make build